// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTsrd91gcss0xAeTzYWj30BvaKWm6FqcU',
    appId: '1:20175704240:web:aa04d61d4dc8954fcc2b75',
    messagingSenderId: '20175704240',
    projectId: 'lab-14-ffb3e',
    authDomain: 'lab-14-ffb3e.firebaseapp.com',
    storageBucket: 'lab-14-ffb3e.appspot.com',
    measurementId: 'G-XC0CDLT7ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaSWvBf_Z64gl18ZvVE58pP7mIdswvpRQ',
    appId: '1:20175704240:android:fe8d65e1667b3acecc2b75',
    messagingSenderId: '20175704240',
    projectId: 'lab-14-ffb3e',
    storageBucket: 'lab-14-ffb3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVRpXUDAj2gr-ejsQjLGhiMEKLw-lDFAw',
    appId: '1:20175704240:ios:df1dde8bd3a547becc2b75',
    messagingSenderId: '20175704240',
    projectId: 'lab-14-ffb3e',
    storageBucket: 'lab-14-ffb3e.appspot.com',
    iosClientId: '20175704240-rm6lpnp2couq87nc55fc5mjs3nttm9l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVRpXUDAj2gr-ejsQjLGhiMEKLw-lDFAw',
    appId: '1:20175704240:ios:df1dde8bd3a547becc2b75',
    messagingSenderId: '20175704240',
    projectId: 'lab-14-ffb3e',
    storageBucket: 'lab-14-ffb3e.appspot.com',
    iosClientId: '20175704240-rm6lpnp2couq87nc55fc5mjs3nttm9l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab14',
  );
}
